### ISSUE TITLE
Suggestion box appears even there is no suggestion to display

### ISSUE THREAD

**Issue by govindarajkp** [web-slate/google-search-clone-web#58]
![image](https://user-images.githubusercontent.com/16048888/158524783-50e14958-e5f0-4164-b6c4-73501e86344a.png)

Google behavior on invalid search char

![image](https://user-images.githubusercontent.com/16048888/158524962-bdaa9455-839b-4ec1-8b81-24f90ca85066.png)

**Comment by sriramanvellingiri** [comment]
As per the latest build this is fixed.

copy: @naveenvignesh5
